// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package main

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (P) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*P) UnmarshalJSON([]byte) error        { return nil }
func (P) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*P) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_P *P
